#!/usr/bin/env bash
# install.sh — Install proxyd as a systemd service
#
# Usage:
#   sudo ./scripts/install.sh               # auto-detect binary at ./build/proxyd
#   sudo ./scripts/install.sh /path/to/bin  # use a specific pre-built binary
#
# Environment overrides (optional):
#   INSTALL_DIR=/opt/proxyd   Installation prefix
#   SERVICE_USER=proxyd       System user to run the service
#   API_PORT=8080             proxyd API port
#   MIHOMO_PORT=7890          Mihomo mixed-proxy port

set -euo pipefail

# ── Defaults ──────────────────────────────────────────────────────────────────
INSTALL_DIR="${INSTALL_DIR:-/opt/proxyd}"
SERVICE_USER="${SERVICE_USER:-proxyd}"
SERVICE_GROUP="${SERVICE_GROUP:-proxyd}"
SERVICE_FILE="/etc/systemd/system/proxyd.service"
API_PORT="${API_PORT:-8080}"
MIHOMO_PORT="${MIHOMO_PORT:-7890}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
step()  { echo -e "\n${CYAN}▶ $*${NC}"; }

# ── Root check ────────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    error "Run with sudo or as root."
    exit 1
fi

# ── Locate binary ─────────────────────────────────────────────────────────────
BINARY_SRC="${1:-}"
if [[ -z "$BINARY_SRC" ]]; then
    if [[ -x "$REPO_ROOT/build/proxyd" ]]; then
        BINARY_SRC="$REPO_ROOT/build/proxyd"
    elif [[ -x "$REPO_ROOT/release/proxyd" ]]; then
        BINARY_SRC="$REPO_ROOT/release/proxyd"
    else
        error "No pre-built binary found."
        error "Run 'make build-all' first, or pass the binary path as an argument:"
        error "  sudo $0 /path/to/proxyd"
        exit 1
    fi
fi

if [[ ! -x "$BINARY_SRC" ]]; then
    error "Binary not found or not executable: $BINARY_SRC"
    exit 1
fi

UPGRADE=false
if [[ -f "$INSTALL_DIR/bin/proxyd" ]]; then
    UPGRADE=true
    warn "Existing installation detected at $INSTALL_DIR — upgrading."
fi

# ── System user ───────────────────────────────────────────────────────────────
step "Setting up system user '$SERVICE_USER'"
if ! getent group "$SERVICE_GROUP" &>/dev/null; then
    groupadd --system "$SERVICE_GROUP"
    info "Created group: $SERVICE_GROUP"
fi
if ! getent passwd "$SERVICE_USER" &>/dev/null; then
    useradd --system \
            --gid "$SERVICE_GROUP" \
            --no-create-home \
            --shell /usr/sbin/nologin \
            --comment "proxyd service account" \
            "$SERVICE_USER"
    info "Created user: $SERVICE_USER"
fi

# ── Directory structure ───────────────────────────────────────────────────────
step "Creating directory structure under $INSTALL_DIR"
install -d -m 755 "$INSTALL_DIR/bin"
install -d -m 750 -o "$SERVICE_USER" -g "$SERVICE_GROUP" \
    "$INSTALL_DIR/data/db" \
    "$INSTALL_DIR/data/mihomo" \
    "$INSTALL_DIR/data/generated" \
    "$INSTALL_DIR/data/cache" \
    "$INSTALL_DIR/logs"

# ── Binary ────────────────────────────────────────────────────────────────────
step "Installing binary"
install -m 755 "$BINARY_SRC" "$INSTALL_DIR/bin/proxyd"
info "Installed: $INSTALL_DIR/bin/proxyd"

# ── Config ────────────────────────────────────────────────────────────────────
step "Configuring"
CONFIG_FILE="$INSTALL_DIR/config.yaml"

if [[ "$UPGRADE" == true && -f "$CONFIG_FILE" ]]; then
    info "Keeping existing config: $CONFIG_FILE"
else
    JWT_SECRET="$(openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -d '\n')"

    cat > "$CONFIG_FILE" <<YAML
# proxyd configuration — generated by install.sh
# Edit then restart: systemctl restart proxyd

server:
  host: "127.0.0.1"
  port: ${API_PORT}
  enable_cors: false

database:
  path: "${INSTALL_DIR}/data/db/proxyd.db"
  foreign_keys: true

mihomo:
  binary_path: ""          # empty = use mihomo alongside proxyd binary
  config_dir: "${INSTALL_DIR}/data/mihomo"
  api_port: 9090
  api_secret: ""
  log_dir: "${INSTALL_DIR}/logs"
  auto_update_enabled: false
  auto_update_check_on_start: false
  release_api: "https://api.github.com/repos/MetaCubeX/mihomo/releases/latest"
  download_dir: "${INSTALL_DIR}/bin"

auth:
  jwt_secret: "${JWT_SECRET}"
  session_timeout: 86400
  max_login_attempts: 5
  lockout_duration: 300

logging:
  level: "info"
  output: "file"
  file_path: "${INSTALL_DIR}/logs/proxyd.log"
  max_size: 100
  max_backups: 5
  max_age: 14
  compress: true

subscription:
  default_interval: 3600
  timeout: 30
  user_agent: "clash.meta"
  max_retries: 3
  retry_delay: 5

policy:
  mixed_port: ${MIHOMO_PORT}
  allow_lan: false
  bind_address: "127.0.0.1"
  log_level: "info"
  mode: "rule"
  external_controller: "127.0.0.1:9090"
  ipv6: false

scheduler:
  enabled: true
  workers: 3
YAML
    chmod 640 "$CONFIG_FILE"
    info "Created config: $CONFIG_FILE"
    info "JWT secret auto-generated. Change default password after first login."
fi

# ── Permissions ───────────────────────────────────────────────────────────────
chown root:"$SERVICE_GROUP" "$CONFIG_FILE"
chown -R "$SERVICE_USER":"$SERVICE_GROUP" \
    "$INSTALL_DIR/data" \
    "$INSTALL_DIR/logs"

# ── Initialise database ───────────────────────────────────────────────────────
step "Initialising database"
DB_PATH="$INSTALL_DIR/data/db/proxyd.db"
if [[ ! -f "$DB_PATH" ]]; then
    sudo -u "$SERVICE_USER" "$INSTALL_DIR/bin/proxyd" \
        -c "$CONFIG_FILE" -init-db
    info "Database initialised: $DB_PATH"
else
    info "Database already exists — skipping init."
fi

# ── systemd service ───────────────────────────────────────────────────────────
step "Installing systemd service"

# Generate service file from template (substitute INSTALL_DIR and SERVICE_USER)
TEMPLATE="$REPO_ROOT/deployments/systemd/proxyd.service"
if [[ -f "$TEMPLATE" ]]; then
    sed \
        -e "s|/opt/proxyd|${INSTALL_DIR}|g" \
        -e "s|User=proxyd|User=${SERVICE_USER}|g" \
        -e "s|Group=proxyd|Group=${SERVICE_GROUP}|g" \
        "$TEMPLATE" > "$SERVICE_FILE"
else
    # Inline fallback if template not available (e.g. binary-only install)
    cat > "$SERVICE_FILE" <<UNIT
[Unit]
Description=Proxyd - Mihomo Proxy Manager
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_GROUP}
WorkingDirectory=${INSTALL_DIR}
EnvironmentFile=-${INSTALL_DIR}/proxyd.env
ExecStart=${INSTALL_DIR}/bin/proxyd -c ${INSTALL_DIR}/config.yaml
Restart=always
RestartSec=3s
TimeoutStopSec=15s
LimitNOFILE=65535
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${INSTALL_DIR}/data ${INSTALL_DIR}/logs
StandardOutput=journal
StandardError=journal
SyslogIdentifier=proxyd

[Install]
WantedBy=multi-user.target
UNIT
fi
chmod 644 "$SERVICE_FILE"
info "Service file: $SERVICE_FILE"

systemctl daemon-reload
systemctl enable proxyd

# ── (Re)start ─────────────────────────────────────────────────────────────────
step "Starting service"
if systemctl is-active --quiet proxyd; then
    systemctl restart proxyd
    info "Service restarted."
else
    systemctl start proxyd
    info "Service started."
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║          proxyd installed successfully!              ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Web UI  : http://127.0.0.1:${API_PORT}"
echo -e "  Login   : admin / admin  (change after first login!)"
echo -e "  Config  : ${CONFIG_FILE}"
echo -e "  Logs    : journalctl -u proxyd -f"
echo ""
echo -e "  ${CYAN}Service commands:${NC}"
echo -e "    systemctl status  proxyd"
echo -e "    systemctl restart proxyd"
echo -e "    systemctl stop    proxyd"
echo ""
if [[ "$UPGRADE" == false ]]; then
    warn "First-time setup: edit ${CONFIG_FILE} and restart the service."
    warn "Then go to Mihomo page to download the mihomo binary."
fi
